name: Python tests

on:
  push:
  pull_request:
  schedule:
    - cron: '3 15 * * SUN'

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install -e git+https://github.com/maxmind/GeoIP2-python#egg=geoip2

      - name: Test
        run: python setup.py test
